CREATE DATABASE customer_behavior;
USE customer_behavior;

-- Q1. What is the total revenue generated by mas vs female customers?

SELECT gender,sum(purchase_amount) total_revenue 
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount

SELECT customer_id , purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);


-- Q3. Which are the top 5 proudcts with the highest average review rating?

SELECT item_purchased , ROUND(AVG(review_rating),2)  Average_Product_Rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping

SELECT shipping_type , ROUND(AVG(purchase_amount),2) Average_Purchase_Amounts_Shipping
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) DESC;

-- Q5. Do subsribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers

SELECT subscription_status ,COUNT(customer_id) Total_Customers, ROUND(AVG(purchase_amount),2) Avg_Spend , ROUND(SUM(purchase_amount),2) Total_Revenu
FROM customer
GROUP BY subscription_status
ORDER BY Avg_Spend , Total_Revenu DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased , ROUND(SUM(IF(discount_applied = 'Yes' , 1 , 0)) * 100 /  COUNT(*),2) discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New , Returning , and Loyal based on their total number of previous purchases,and show the count of each segment

SELECT customer_segment , COUNT(*) Total_Customer
FROM (
	SELECT customer_id , previous_purchases ,IF(previous_purchases = 1 , 'New' ,IF(previous_purchases BETWEEN 2 AND 10 , 'Returning','Loyal')) customer_segment
	FROM customer
    )CS
GROUP BY customer_segment
ORDER BY Total_Customer;

-- Q8. What are the top 3 most purchased products within each category

SELECT item_rank, category, item_purchased, total_orders
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id)  total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) item_rank
    FROM customer
    GROUP BY category, item_purchased
	)  item_counts
    
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT group_ , CONCAT(ROUND( (SUM(IF(subscription_status = 'Yes',1,0))* 100)  / (COUNT(customer_id) ) , 1),'%') subscription_rate
FROM (
	SELECT customer_id ,previous_purchases ,IF(previous_purchases > 5 , 'Repeat_buyers','Non_repeat_buyers') group_ , subscription_status
	FROM customer
    )result
GROUP BY group_;

-- Q10. What is the revenue contribution of each age group? 

SELECT  age_group , SUM(purchase_amount) total_revenue 
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;